#!/usr/bin/env python3
"""One-shot patch for TransitionWnd.cpp: drag-drop, context menu, subclass."""

file_cpp = r"c:\Users\Noah Jorgensen\Documents\SWS Project\sws-master\reaper-transition-snapshots\TransitionWnd.cpp"
file_rc  = r"c:\Users\Noah Jorgensen\Documents\SWS Project\sws-master\reaper-transition-snapshots\reaper_transitions.rc"

# ─── TransitionWnd.cpp ────────────────────────────────────────────────────────
with open(file_cpp, 'rb') as f:
    raw = f.read()
has_crlf = b'\r\n' in raw
cpp = raw.decode('utf-8').replace('\r\n', '\n')

def check(label, old, text):
    if old not in text:
        print(f"MISSING: {label}")
        print(f"  Looking for: {repr(old[:80])}")
    else:
        print(f"OK: {label}")
    return old in text

# ── 1. CTX enum ──────────────────────────────────────────────────────────────
OLD1 = 'enum { CTX_RENAME = 100, CTX_OVERWRITE, CTX_DELETE };'
NEW1 = ('enum { CTX_RENAME = 100, CTX_OVERWRITE, CTX_DELETE,\n'
        '       CTX_RECALL_CTX, CTX_COPY_CTX, CTX_PASTE_CTX, CTX_ADDSPACER };')
check("CTX enum", OLD1, cpp)
cpp = cpp.replace(OLD1, NEW1)

# ── 2. Drag + subclass globals ────────────────────────────────────────────────
OLD2 = 'static RECT g_listInitRect = {};\n\n// -----------'
NEW2 = ('static RECT g_listInitRect = {};\n\n'
        '// Drag-and-drop reorder state\n'
        'static int        g_dragSrc     = -1;\n'
        'static int        g_dragTarget  = -1;\n'
        'static HIMAGELIST g_hDragImages = nullptr;\n\n'
        '// List subclass state\n'
        'static WNDPROC s_origListProc = nullptr;\n'
        'static bool    s_lbTracking   = false;\n'
        'static POINT   s_lbDownPt     = {};\n'
        'static int     s_lbDownItem   = -1;\n\n'
        '// -----------')
check("drag globals anchor", OLD2, cpp)
cpp = cpp.replace(OLD2, NEW2)

# ── 3. ShowContextMenu + DoEndDrag + ListSubclassProc ─────────────────────────
OLD3 = (
'static void ShowContextMenu(HWND hwnd, int item, POINT pt)\n'
'{\n'
'    if (item < 0) return;\n'
'\n'
'    HMENU hMenu = CreatePopupMenu();\n'
'    AppendMenu(hMenu, MF_STRING,    CTX_RENAME,    "Rename");\n'
'    AppendMenu(hMenu, MF_STRING,    CTX_OVERWRITE, "Overwrite (re-capture)");\n'
'    AppendMenu(hMenu, MF_SEPARATOR, 0,             nullptr);\n'
'    AppendMenu(hMenu, MF_STRING,    CTX_DELETE,    "Delete");\n'
'\n'
'    int cmd = TrackPopupMenu(hMenu, TPM_RETURNCMD | TPM_RIGHTBUTTON,\n'
'                              pt.x, pt.y, 0, hwnd, nullptr);\n'
'    DestroyMenu(hMenu);\n'
'\n'
'    if (cmd == CTX_RENAME && item >= 0 && item < (int)g_snapshots.size())\n'
'    {\n'
'        ListView_EditLabel(GetDlgItem(hwnd, IDC_LIST), item);\n'
'    }\n'
'    else if (cmd == CTX_OVERWRITE && item >= 0 && item < (int)g_snapshots.size())\n'
'    {\n'
'        g_snapshots[item]->Capture(TS_CAPTURE_ALL);\n'
'        RefreshListView(hwnd);\n'
'        Undo_OnStateChangeEx("Overwrite Scene", -1, -1);\n'
'    }\n'
'    else if (cmd == CTX_DELETE && item >= 0 && item < (int)g_snapshots.size())\n'
'    {\n'
'        g_snapshots.erase(g_snapshots.begin() + item);\n'
'        for (int i = 0; i < (int)g_snapshots.size(); i++)\n'
'            g_snapshots[i]->m_slot = i;\n'
'        RefreshListView(hwnd);\n'
'        LoadEditorFromSnapshot(hwnd, nullptr);\n'
'        Undo_OnStateChangeEx("Delete Scene", -1, -1);\n'
'    }\n'
'}\n'
'\n'
'// ---------------------------------------------------------------------------\n'
'// DialogProc\n'
'// ---------------------------------------------------------------------------\n'
'static INT_PTR CALLBACK DialogProc'
)

NEW3 = (
'static void ShowContextMenu(HWND hwnd, int item, POINT pt)\n'
'{\n'
'    const bool hasItem  = (item >= 0 && item < (int)g_snapshots.size());\n'
'    const bool isSpacer = hasItem && g_snapshots[item]->m_isSpacer;\n'
'    const bool hasClip  = (g_clipboard != nullptr);\n'
'\n'
'    HMENU hMenu = CreatePopupMenu();\n'
'    AppendMenu(hMenu, MF_STRING | (hasItem && !isSpacer ? 0 : MF_GRAYED),\n'
'               CTX_RECALL_CTX,  "Recall");\n'
'    AppendMenu(hMenu, MF_SEPARATOR, 0, nullptr);\n'
'    AppendMenu(hMenu, MF_STRING | (hasItem && !isSpacer ? 0 : MF_GRAYED),\n'
'               CTX_COPY_CTX,    "Copy");\n'
'    AppendMenu(hMenu, MF_STRING | (hasClip ? 0 : MF_GRAYED),\n'
'               CTX_PASTE_CTX,   "Paste After");\n'
'    AppendMenu(hMenu, MF_STRING | (hasItem && !isSpacer ? 0 : MF_GRAYED),\n'
'               CTX_OVERWRITE,   "Overwrite (re-capture)");\n'
'    AppendMenu(hMenu, MF_STRING | (hasItem && !isSpacer ? 0 : MF_GRAYED),\n'
'               CTX_RENAME,      "Rename");\n'
'    AppendMenu(hMenu, MF_SEPARATOR, 0, nullptr);\n'
'    AppendMenu(hMenu, MF_STRING | (hasItem ? 0 : MF_GRAYED),\n'
'               CTX_DELETE,      "Delete");\n'
'    AppendMenu(hMenu, MF_SEPARATOR, 0, nullptr);\n'
'    AppendMenu(hMenu, MF_STRING, CTX_ADDSPACER, "Add Spacer Below");\n'
'\n'
'    int cmd = TrackPopupMenu(hMenu, TPM_RETURNCMD | TPM_RIGHTBUTTON,\n'
'                              pt.x, pt.y, 0, hwnd, nullptr);\n'
'    DestroyMenu(hMenu);\n'
'\n'
'    if (cmd == CTX_RECALL_CTX)\n'
'    {\n'
'        if (hasItem && !isSpacer) DoRecall(hwnd, item);\n'
'    }\n'
'    else if (cmd == CTX_COPY_CTX)\n'
'    {\n'
'        if (hasItem && !isSpacer)\n'
'            g_clipboard = std::make_unique<TransitionSnapshot>(*g_snapshots[item]);\n'
'    }\n'
'    else if (cmd == CTX_PASTE_CTX)\n'
'    {\n'
'        if (!g_clipboard) return;\n'
'        int insertAt = hasItem ? item + 1 : (int)g_snapshots.size();\n'
'        auto copy = std::make_unique<TransitionSnapshot>(*g_clipboard);\n'
'        if (copy->m_name.find(" (copy)") == std::string::npos)\n'
'            copy->m_name += " (copy)";\n'
'        copy->m_time = (int)std::time(nullptr);\n'
'        g_snapshots.insert(g_snapshots.begin() + insertAt, std::move(copy));\n'
'        for (int i = 0; i < (int)g_snapshots.size(); i++) g_snapshots[i]->m_slot = i;\n'
'        RefreshListView(hwnd);\n'
'        HWND hList = GetDlgItem(hwnd, IDC_LIST);\n'
'        ListView_SetItemState(hList, insertAt,\n'
'            LVIS_SELECTED | LVIS_FOCUSED, LVIS_SELECTED | LVIS_FOCUSED);\n'
'        ListView_EnsureVisible(hList, insertAt, FALSE);\n'
'        Undo_OnStateChangeEx("Paste Scene", -1, -1);\n'
'    }\n'
'    else if (cmd == CTX_OVERWRITE)\n'
'    {\n'
'        if (hasItem && !isSpacer)\n'
'        {\n'
'            g_snapshots[item]->Capture(TS_CAPTURE_ALL);\n'
'            g_snapshots[item]->m_time = (int)std::time(nullptr);\n'
'            RefreshListView(hwnd);\n'
'            Undo_OnStateChangeEx("Overwrite Scene", -1, -1);\n'
'        }\n'
'    }\n'
'    else if (cmd == CTX_RENAME)\n'
'    {\n'
'        if (hasItem && !isSpacer)\n'
'            ListView_EditLabel(GetDlgItem(hwnd, IDC_LIST), item);\n'
'    }\n'
'    else if (cmd == CTX_DELETE)\n'
'    {\n'
'        if (hasItem)\n'
'        {\n'
'            g_snapshots.erase(g_snapshots.begin() + item);\n'
'            for (int i = 0; i < (int)g_snapshots.size(); i++)\n'
'                g_snapshots[i]->m_slot = i;\n'
'            RefreshListView(hwnd);\n'
'            LoadEditorFromSnapshot(hwnd, nullptr);\n'
'            Undo_OnStateChangeEx("Delete Scene", -1, -1);\n'
'        }\n'
'    }\n'
'    else if (cmd == CTX_ADDSPACER)\n'
'    {\n'
'        int insertAfter = hasItem ? item + 1 : (int)g_snapshots.size();\n'
'        auto spacer = std::make_unique<TransitionSnapshot>(insertAfter, "--- spacer ---");\n'
'        spacer->m_isSpacer = true;\n'
'        g_snapshots.insert(g_snapshots.begin() + insertAfter, std::move(spacer));\n'
'        for (int i = 0; i < (int)g_snapshots.size(); i++) g_snapshots[i]->m_slot = i;\n'
'        RefreshListView(hwnd);\n'
'    }\n'
'}\n'
'\n'
'// ---------------------------------------------------------------------------\n'
'// DoEndDrag – commit the drag-to-reorder\n'
'// ---------------------------------------------------------------------------\n'
'static void DoEndDrag(HWND dlg)\n'
'{\n'
'    HWND hList = GetDlgItem(dlg, IDC_LIST);\n'
'\n'
'    if (g_hDragImages)\n'
'    {\n'
'        ImageList_DragLeave(dlg);\n'
'        ImageList_EndDrag();\n'
'        ImageList_Destroy(g_hDragImages);\n'
'        g_hDragImages = nullptr;\n'
'    }\n'
'    ListView_SetItemState(hList, -1, 0, LVIS_DROPHILITED);\n'
'\n'
'    int src = g_dragSrc;\n'
'    int tgt = g_dragTarget;\n'
'    g_dragSrc    = -1;\n'
'    g_dragTarget = -1;\n'
'\n'
'    if (src < 0 || tgt < 0 || src == tgt) return;\n'
'    if (src >= (int)g_snapshots.size() || tgt >= (int)g_snapshots.size()) return;\n'
'\n'
'    auto moved = std::move(g_snapshots[src]);\n'
'    g_snapshots.erase(g_snapshots.begin() + src);\n'
'    // After erasing src, adjust tgt if src was before tgt\n'
'    int insertAt = (src < tgt) ? tgt - 1 : tgt;\n'
'    if (insertAt >= (int)g_snapshots.size())\n'
'        g_snapshots.push_back(std::move(moved));\n'
'    else\n'
'        g_snapshots.insert(g_snapshots.begin() + insertAt, std::move(moved));\n'
'\n'
'    for (int i = 0; i < (int)g_snapshots.size(); i++)\n'
'        g_snapshots[i]->m_slot = i;\n'
'\n'
'    RefreshListView(dlg);\n'
'    ListView_SetItemState(hList, insertAt,\n'
'        LVIS_SELECTED | LVIS_FOCUSED, LVIS_SELECTED | LVIS_FOCUSED);\n'
'    ListView_EnsureVisible(hList, insertAt, FALSE);\n'
'    Undo_OnStateChangeEx("Reorder Scene", -1, -1);\n'
'}\n'
'\n'
'// ---------------------------------------------------------------------------\n'
'// ListSubclassProc – intercept mouse on list for drag-drop and right-click\n'
'// ---------------------------------------------------------------------------\n'
'static LRESULT CALLBACK ListSubclassProc(HWND hList, UINT msg,\n'
'                                          WPARAM wParam, LPARAM lParam)\n'
'{\n'
'    HWND dlg = GetParent(hList);\n'
'\n'
'    switch (msg)\n'
'    {\n'
'    case WM_LBUTTONDOWN:\n'
'    {\n'
'        LRESULT r = CallWindowProc(s_origListProc, hList, msg, wParam, lParam);\n'
'        LVHITTESTINFO hti = {};\n'
'        hti.pt = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam) };\n'
'        int item = ListView_HitTest(hList, &hti);\n'
'        if (item >= 0)\n'
'        {\n'
'            s_lbTracking = true;\n'
'            s_lbDownPt   = hti.pt;\n'
'            s_lbDownItem = item;\n'
'            SetCapture(hList);\n'
'        }\n'
'        return r;\n'
'    }\n'
'\n'
'    case WM_MOUSEMOVE:\n'
'    {\n'
'        POINT pt = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam) };\n'
'\n'
'        if (s_lbTracking && g_dragSrc < 0)\n'
'        {\n'
'            if (abs(pt.x - s_lbDownPt.x) > GetSystemMetrics(SM_CXDRAG) ||\n'
'                abs(pt.y - s_lbDownPt.y) > GetSystemMetrics(SM_CYDRAG))\n'
'            {\n'
'                g_dragSrc    = s_lbDownItem;\n'
'                g_dragTarget = -1;\n'
'                s_lbTracking = false;\n'
'\n'
'                POINT ptOffset = { 8, 8 };\n'
'                g_hDragImages = ListView_CreateDragImage(hList, g_dragSrc, &ptOffset);\n'
'                if (g_hDragImages)\n'
'                {\n'
'                    POINT dlgPt = pt;\n'
'                    ClientToScreen(hList, &dlgPt);\n'
'                    ScreenToClient(dlg, &dlgPt);\n'
'                    ImageList_BeginDrag(g_hDragImages, 0, 8, 8);\n'
'                    ImageList_DragEnter(dlg, dlgPt.x, dlgPt.y);\n'
'                }\n'
'            }\n'
'        }\n'
'\n'
'        if (g_dragSrc >= 0)\n'
'        {\n'
'            POINT dlgPt = pt;\n'
'            ClientToScreen(hList, &dlgPt);\n'
'            ScreenToClient(dlg, &dlgPt);\n'
'            if (g_hDragImages)\n'
'            {\n'
'                ImageList_DragMove(dlgPt.x, dlgPt.y);\n'
'                ImageList_DragShowNolock(FALSE);\n'
'            }\n'
'            LVHITTESTINFO hti = {};\n'
'            hti.pt = pt;\n'
'            int newTgt = ListView_HitTest(hList, &hti);\n'
'            if (newTgt != g_dragTarget)\n'
'            {\n'
'                g_dragTarget = newTgt;\n'
'                ListView_SetItemState(hList, -1, 0, LVIS_DROPHILITED);\n'
'                if (g_dragTarget >= 0)\n'
'                    ListView_SetItemState(hList, g_dragTarget,\n'
'                                         LVIS_DROPHILITED, LVIS_DROPHILITED);\n'
'            }\n'
'            if (g_hDragImages)\n'
'                ImageList_DragShowNolock(TRUE);\n'
'            return 0;\n'
'        }\n'
'        break;\n'
'    }\n'
'\n'
'    case WM_RBUTTONUP:\n'
'    {\n'
'        // Intercept here so NM_RCLICK never reaches REAPER\'s host window\n'
'        POINT pt = { GET_X_LPARAM(lParam), GET_Y_LPARAM(lParam) };\n'
'        LVHITTESTINFO hti = {};\n'
'        hti.pt = pt;\n'
'        int hitItem = ListView_HitTest(hList, &hti);\n'
'        POINT screenPt = pt;\n'
'        ClientToScreen(hList, &screenPt);\n'
'        ShowContextMenu(dlg, hitItem, screenPt);\n'
'        return 0;\n'
'    }\n'
'\n'
'    case WM_LBUTTONUP:\n'
'        s_lbTracking = false;\n'
'        ReleaseCapture();\n'
'        if (g_dragSrc >= 0)\n'
'        {\n'
'            DoEndDrag(dlg);\n'
'            return 0;\n'
'        }\n'
'        break;\n'
'\n'
'    case WM_CAPTURECHANGED:\n'
'        s_lbTracking = false;\n'
'        if (g_dragSrc >= 0)\n'
'            DoEndDrag(dlg);\n'
'        break;\n'
'    }\n'
'\n'
'    return CallWindowProc(s_origListProc, hList, msg, wParam, lParam);\n'
'}\n'
'\n'
'// ---------------------------------------------------------------------------\n'
'// DialogProc\n'
'// ---------------------------------------------------------------------------\n'
'static INT_PTR CALLBACK DialogProc'
)

check("ShowContextMenu block", OLD3, cpp)
cpp = cpp.replace(OLD3, NEW3)

# ── 4. Install subclass after column setup in WM_INITDIALOG ──────────────────
OLD4 = ('            col.cx = 75;  col.pszText = const_cast<char*>("Saved");\n'
        '            ListView_InsertColumn(hList, 2, &col);\n'
        '        }')
NEW4 = ('            col.cx = 75;  col.pszText = const_cast<char*>("Saved");\n'
        '            ListView_InsertColumn(hList, 2, &col);\n'
        '\n'
        '            // Subclass for drag-drop + right-click interception\n'
        '            s_origListProc = (WNDPROC)(LONG_PTR)SetWindowLongPtr(\n'
        '                hList, GWLP_WNDPROC, (LONG_PTR)ListSubclassProc);\n'
        '        }')
check("subclass install anchor", OLD4, cpp)
cpp = cpp.replace(OLD4, NEW4)

# ── 5. Remove NM_RCLICK from WM_NOTIFY (subclass handles it now) ─────────────
OLD5 = ('            else if (hdr->code == NM_RCLICK)\n'
        '            {\n'
        '                NMITEMACTIVATE* nia = (NMITEMACTIVATE*)lParam;\n'
        '                POINT pt;\n'
        '                GetCursorPos(&pt);\n'
        '                ShowContextMenu(hwnd, nia->iItem, pt);\n'
        '            }\n')
check("NM_RCLICK block", OLD5, cpp)
cpp = cpp.replace(OLD5, '')

# ── 6. Restore subclass in WM_DESTROY ────────────────────────────────────────
OLD6 = ('    case WM_DESTROY:\n'
        '        KillTimer(hwnd, UI_TIMER_ID);')
NEW6 = ('    case WM_DESTROY:\n'
        '        KillTimer(hwnd, UI_TIMER_ID);\n'
        '        if (s_origListProc)\n'
        '        {\n'
        '            HWND hListD = GetDlgItem(hwnd, IDC_LIST);\n'
        '            if (hListD) SetWindowLongPtr(hListD, GWLP_WNDPROC, (LONG_PTR)s_origListProc);\n'
        '            s_origListProc = nullptr;\n'
        '        }')
check("WM_DESTROY anchor", OLD6, cpp)
cpp = cpp.replace(OLD6, NEW6)

# ── Write TransitionWnd.cpp ───────────────────────────────────────────────────
out = cpp.replace('\n', '\r\n') if has_crlf else cpp
with open(file_cpp, 'wb') as f:
    f.write(out.encode('utf-8'))
print("TransitionWnd.cpp written")

# ─── reaper_transitions.rc ────────────────────────────────────────────────────
with open(file_rc, 'rb') as f:
    raw_rc = f.read()
has_crlf_rc = b'\r\n' in raw_rc
rc = raw_rc.decode('utf-8').replace('\r\n', '\n')

# Restore "Cue List" (was changed to "TEST BUILD 1" for testing)
rc = rc.replace('"TEST BUILD 1"', '"Cue List"')

out_rc = rc.replace('\n', '\r\n') if has_crlf_rc else rc
with open(file_rc, 'wb') as f:
    f.write(out_rc.encode('utf-8'))
print("reaper_transitions.rc written")

print("\nAll done.")
